### PR TITLE
rework quality

### PR DESCRIPTION
**Pull request by ingwinlu**
rework how qualities in M3UPlaylist are handled.

* find best match quality over distance between selected/available qualities
* make sure playlist has at least one parsed value else throw an ValueError
* add test for valueerror

### CODE REVIEW

**Comment by MrSprigster** [comment]
Looks good to me.

**Comment by MrSprigster** [comment]
Is there currently an instance where the nearest available quality will be used as opposed to the best available?

**Comment by ingwinlu** [comment]
@MrSprigster you mean a test case like this: 3937f48 ?

on a more general note: i am not aware if twitch ever produces such output, i.e. restricting lower qualities but offering better ones without.

i am hesitant to just deliver the 'best' available quality in such a case though, since if you selected a lower quality you do that because you have a reason to, so a lower quality is probably prefered to a good one

**Comment by MrSprigster** [comment]
It's definitely an advantage to have that ability within the addon just in case Twitch decides to start offering a wider range of qualities to streamers. However unfortunately I don't anticipate this enhancement being utilised any time soon simply due to the way Twitch does things :(.

:+1: for the good coding practice though. Hopefully Twitch will follow suit at some point.

Sprig

**Comment by MrSprigster** [comment]
Drop me a pull request when you're ready and I'll merge.

Thanks again for your work on this,

Sprig :100:

**Pull request merged**
