### PR TITLE
Fix this for python 3

### PR DESCRIPTION
**Pull request by shughes-uk**
There is no readall() for python 3 , read() is what you need

### CODE REVIEW

**Comment by shughes-uk** [comment]
No idea why this is failing on python2.7 when no changes that should affect it have been commited

**Comment by ingwinlu** [comment]
did not see this one first, see my response in https://github.com/ingwinlu/python-twitch/pull/28

**Comment by ingwinlu** [comment]
Also you should never open PR's from your master branch. It is a recipe for disaster and makes rebasing a lot more complicated.

**Comment by ingwinlu** [comment]
closed in favour of #28

**Pull request closed without merging**
