### PR TITLE
Make compatible with python3.5

### PR DESCRIPTION
**Pull request by panzi**
Its response.read() in Python 3 just like in Python 2.

### CODE REVIEW

**Comment by ingwinlu** [comment]
That is not a python3 issue, it is specific to >python3.5. If you update your commit message to include a better description of the cause I will happily merge it. Else I will push one myself.

**Comment by ingwinlu** [comment]
See https://travis-ci.org/ingwinlu/python-twitch/builds/100302785 for confirmation.

**Comment by panzi** [comment]
Like this?

**Comment by ingwinlu** [comment]
https://github.com/erlang/otp/wiki/Writing-good-commit-messages
or
http://chris.beams.io/posts/git-commit/
give good ideas on how commit messages should be written.

**Comment by ingwinlu** [comment]
ty

**Pull request merged**
