### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by MrSprigster**

### CODE REVIEW

**Comment by ingwinlu** [comment]
already cherrypicked your commit from upstream :)

**Comment by MrSprigster** [comment]
Cool :+1: :)

**Comment by ingwinlu** [comment]
the problem with that solution is that it isn't best match anymore, it just gets the best available resolution instead of the closest one to what you want

**Comment by MrSprigster** [comment]
That's true but at the moment it seems to be a boolean, Twitch either provides transcoding (to all qualities) or none (just provides source).

**Comment by ingwinlu** [comment]
don't forget about restricted streams though

**Comment by MrSprigster** [comment]
Ideally (due to current lack of user auth) restricted qualities should be ignored and never reach the getQuality function. 

They are defined as EXT-X-TWITCH-RESTRICTED and the lines that contained this were dropped in previous versions.

Sprig

**Comment by MrSprigster** [comment]
And it looks like they still are :) 

if(line.startswith('#EXT-X-MEDIA')):

**Comment by ingwinlu** [comment]
@MrSprigster do you mind reviewing #5?

**Pull request closed without merging**
